### ISSUE TITLE
Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>

### ISSUE THREAD

**Issue by raeperd** [raeperd/raeperd.github.io#61]
Error log

```
next-dev.js?3515:32 Warning: validateDOMNesting(...): <tr> cannot appear as a child of <table>. Add a <tbody>, <thead> or <tfoot> to your code to match the DOM tree generated by the browser.
    at tr
    at table
    at NoteTableNav (webpack-internal:///./components/TaggedNoteTableView.tsx:251:21)
    at TaggedNoteTableView (webpack-internal:///./components/TaggedNoteTableView.tsx:202:22)
    at main
    at Layout (webpack-internal:///./pages/_app.tsx:665:24)
    at MyApp (webpack-internal:///./pages/_app.tsx:591:24)
    at ErrorBoundary (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:20584)
    at ReactDevOverlay (webpack-internal:///./node_modules/next/dist/compiled/@next/react-dev-overlay/client.js:8:23125)
    at Container (webpack-internal:///./node_modules/next/dist/client/index.js:300:5)
    at AppContainer (webpack-internal:///./node_modules/next/dist/client/index.js:804:24)
    at Root (webpack-internal:///./node_modules/next/dist/client/index.js:957:26)
window.console.error @ next-dev.js?3515:32
```

**Comment by raeperd** [comment]
According to [Warning: validateDOMNesting(...): `<tr>` cannot appear as a child of `<table>` · Issue #5652 · facebook/react](https://github.com/facebook/react/issues/5652).

> Browsers need the `<tbody>` tag. If it is not in your code, then the browser will automatically insert it. This will work fine on first render, but when the table gets updated, then the DOM tree is different from what React expects. This can give strange bugs, therefore React warns you to insert the `<tbody>`. It is a really helpful warning.
